name: Sync Repo Labels Reusable Workflow
on:
  workflow_call:
    inputs:
      repo-name:
        description: 'Name of the repo'
        required: true
        type: string

jobs:
  repo_setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout template repository
        uses: actions/checkout@v3
        with:
          repository: HeaSoLab/template
          path: template-repo
          ref: main
          token: ${{ secrets.ACTIONS }}
      - uses: micnncim/action-label-syncer@v1
        with:
          manifest: template-repo/.github/labels.yml
          repository: |
            ${{ inputs.repo-name }}
          token: ${{ secrets.ACTIONS }}