name: Sync Repo Labels
on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
  # Run manually.
  workflow_dispatch:

jobs:
  repo_setup:
    runs-on: ubuntu-latest
    steps:
      - uses: HeaSoLab/template/.github/template/repo_sync_labels.yml@main
        with:
          repo-name: 'HeaSoLab/template'